name: point_pillar_intermediate_fusion
root_dir: "/home/amod/OpenCOOD/opv2v/train"
validate_dir: "/home/amod/OpenCOOD/opv2v/train"
yaml_parser: load_point_pillar_params
train_params:
  batch_size: 1
  epoches: 1
  eval_freq: 1
  save_freq: 1
  num_workers: 2
fusion:
  core_method: IntermediateFusionDataset
  args: []
preprocess:
  core_method: SpVoxelPreprocessor
  args:
    voxel_size: &id002
    - 0.4
    - 0.4
    - 4
    max_points_per_voxel: 24
    max_voxel_train: 24000
    max_voxel_test: 50000
  cav_lidar_range: &id001
  - -140.8
  - -40
  - -3
  - 140.8
  - 40
  - 1
data_augment:
- NAME: random_world_flip
  ALONG_AXIS_LIST:
  - x
- NAME: random_world_rotation
  WORLD_ROT_ANGLE:
  - -0.78539816
  - 0.78539816
- NAME: random_world_scaling
  WORLD_SCALE_RANGE:
  - 0.95
  - 1.05
postprocess:
  core_method: VoxelPostprocessor
  anchor_args:
    cav_lidar_range: *id001
    l: 3.9
    w: 1.6
    h: 1.56
    r:
    - 0
    - 90
    feature_stride: 2
    num: 2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.2
  order: hwl
  max_num: 100
  nms_thresh: 0.15
model:
  core_method: point_pillar_intermediate
  args:
    voxel_size: *id002
    lidar_range: *id001
    anchor_number: 2
    pillar_vfe:
      use_norm: true
      with_distance: false
      use_absolute_xyz: true
      num_filters: [64]        # keep 64 here (ok)
    point_pillar_scatter:
      num_features: 64
    base_bev_backbone:
      layer_nums: [3, 5, 8]
      layer_strides: [2, 2, 2]
      num_filters: [48, 96, 192]          # ok to keep as-is
      upsample_strides: [1, 2, 4]
      num_upsample_filter: [128, 128, 128]  # <-- change to match 384 total
      compression: 0
    anchor_num: 2
loss:
  core_method: point_pillar_loss
  args:
    cls_weight: 1.0
    reg: 2.0
optimizer:
  core_method: Adam
  lr: 0.002
  args:
    eps: 1e-10
    weight_decay: 1e-4
lr_scheduler:
  core_method: multistep
  gamma: 0.1
  step_size:
  - 10
  - 15
